title: 'Richard Holland Memorial Scholarship'
author:
  name: 'Corie Miller'
  email: coriem0213@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'The Richard Holland Memorial Scholarship was established to remember the life and legacy of a great man, friend, son, and brother. '
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
